{
  parserClass="edu.team449.lang.YamlParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Yaml"
  psiImplClassSuffix="Impl"
  psiPackage="edu.team449.lang.psi"
  psiImplPackage="edu.team449.lang.psi.impl"

  elementTypeHolderClass="edu.team449.lang.psi.YamlTypes"
  elementTypeClass="edu.team449.lang.psi.YamlElementType"
  tokenTypeClass="edu.team449.lang.psi.YamlTokenType"

  psiImplUtilClass="edu.team449.lang.psi.impl.YamlPsiImplUtil"

  tokens = [
  ]

}

YamlFile ::= x